apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: client
resources:
- namespace.yaml
- ../base/

images:
- name: IMAGE_NAME
  newName: ghcr.io/terotuomala/client
  newTag: 33e0398ae0191121b6865bf2bdf4892a38f1f690
