apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: client
resources:
- namespace.yaml
- ../base/

patchesJson6902:
- path: hpa-patch.yaml
  target:
    group: autoscaling
    kind: HorizontalPodAutoscaler
    name: client
    version: v2beta1

images:
- name: IMAGE_NAME
  newName: ghcr.io/terotuomala/client
  newTag: b4a37c121b94464f2514590c6b3ecc337852cf0a
