apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: client
resources:
- namespace.yaml
- ../base/

patchesJson6902:
- path: hpa-patch.yaml
  target:
    group: autoscaling
    kind: HorizontalPodAutoscaler
    name: client
    version: v2beta1

images:
- name: IMAGE_NAME
  newName: ghcr.io/terotuomala/client
  newTag: d5d9ae607dd4cba7fd0f414f808944786d18e461
