apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: client
resources:
- namespace.yaml
- ../base/

patchesJson6902:
- path: hpa-patch.yaml
  target:
    group: autoscaling
    kind: HorizontalPodAutoscaler
    name: client
    version: v2beta1
- path: pdb-patch.yaml
  target:
    group: policy
    kind: PodDisruptionBudget
    name: client
    version: v1beta1

images:
- name: IMAGE_NAME
  newName: ghcr.io/terotuomala/client
  newTag: 903a9cdda7eb92e1efe747bce963602f1dbbe1e3
