apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: client
resources:
  - deployment.yaml
  - hpa.yaml
  - service.yaml

images:
- name: IMAGE_NAME
  newName: ghcr.io/terotuomala/client
  newTag: 1a1bfe8c40f6b0527e33cfa93212d76924fe4ce1