---
name: lint

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]

env:
    KUSTOMIZE_VERSION: v3.9.3

jobs:
  lint-yaml:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    strategy:
      matrix:
        node: [16]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Lint YAML
      uses: ibiqlik/action-yamllint@v3
      with:
        file_or_dir: "./k8s"
        config_file: "./.github/yamllint.config.yaml"

    - name: Build the k8s manifests using Kustomize
      working-directory: k8s/staging
      run: |-
        ./kustomize build > staging-manifests.yaml

    - name: Scan k8s manifests with kube-linter
      uses: stackrox/kube-linter-action@v1.0.4
      with:
        directory: "./k8s/staging/staging-manifests.yaml"

    - name: Setup Node.js ${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}

    - name: Install dependencies
      run: npm ci

    - name: Lint JS
      run: npm run lint
