name: lint

on:
  pull_request:
    types: [opened, reopened]

jobs:
  lint-yaml:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Lint YAML
      uses: ibiqlik/action-yamllint@v3
      with:
        file_or_dir: "./k8s"
        config_data: |
          extends: default
          rules:
            truthy:
              allowed-values: ['true', 'false', 'on', 'yes']
            comments:
              min-spaces-from-content: 1
            line-length: disable
            braces:
              min-spaces-inside: 0
              max-spaces-inside: 1
            brackets:
              min-spaces-inside: 0
              max-spaces-inside: 0