---
name: lint

on:
  pull_request:
    types: [opened, reopened]
    branches: [main]

jobs:
  lint-yaml:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    strategy:
      matrix:
        node: [14]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Lint YAML
      uses: ibiqlik/action-yamllint@v3
      with:
        file_or_dir: "./k8s"
        config_file: "./.github/yamllint.config.yaml"

    - name: Scan k8s manifests with kube-linter
      uses: stackrox/kube-linter-action@v1.0.3
      with:
        directory: "./k8s"

    - name: Setup Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}

    - name: Install dependencies
      run: npm ci

    - name: Lint JS
      run: npm run lint
