---
name: vulnerability-scan

on:
  schedule:
    - cron: "0 0 * * 1"

permissions: read-all

jobs:
  trivy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Build image
        id: build
        run: |
          IMAGE=test/client:${{ github.sha }}
          docker build -t ${IMAGE} .
          echo "::set-output name=image::$IMAGE"
      
      - name: Scan image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.build.outputs.image }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
