---
name: vulnerability-scan

on:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  trivy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Build image
        id: build
        run: |
          IMAGE=test/client:${{ github.sha }}
          docker build -t ${IMAGE} .
          echo "::set-output name=image::$IMAGE"
      
      - name: Scan image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.build.outputs.image }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
